### ISSUE TITLE
ReferenceError: Parse is not defined

### ISSUE THREAD

**Issue by deden** [flovilmart/parse-image#1]
I got this error:

/Users/username/node_modules/parse-image/index.js:9
       `var p = new Parse.Promise();`
                    ^
ReferenceError: Parse is not defined
    at Image.setData (/Users/username/node_modules/parse-image/index.js:9:14)

**Comment by flovilmart** [comment]
In which context are you using that module?

**Comment by deden** [comment]
here's setup on my main js :
`var Parse = require('parse').Parse;`
`var Image = require("parse-image");`

But in my case it can be fixed temporarily by adding line `var Parse = require('parse').Parse;` inside ...node_modules/parse-image/index.js, 
any suggestion?

**Comment by flovilmart** [comment]
Do you use parse-develop?

**Comment by deden** [comment]
No, 
Currently I'm creating a script for images batch upload to my parse app.

**Comment by flovilmart** [comment]
Ok, that module wasn't meant to be used outside parse develop. 

Wanna make a pull request (and add parse as a dependency in the package)?

**Comment by flovilmart** [comment]
You could also declare a global Parse instead of a var

**Comment by deden** [comment]
Yeah, that's a more elegant way, thanks for solution

**Comment by flovilmart** [comment]
I'll also update the module for a standalone usage as you suggested

**Comment by flovilmart** [comment]
I've pushed an update, fixed some bugs and errors and as well added the pad method to fully comply with Parse.Cloud module
