### ISSUE TITLE
Compatibility with parse server 3.0

### ISSUE THREAD

**Issue by funkenstrahlen** [flovilmart/parse-image#22]
Parse server 3.0 does no longer contain parse promises but uses the JS promises.

```
(node:14) UnhandledPromiseRejectionWarning: TypeError: Parse.Promise is not a constructor
```

**Comment by flovilmart** [comment]
Are you willing to open a Pr and provide a fix?

**Comment by gorillatapstudio** [comment]
do you guys still have plan to fix it any soon? thanks!

**Comment by flovilmart** [comment]
Feel free to open a PR, as stated above. I don’t maintain this project anymore
