### ISSUE TITLE
Deploying parse-image on Heroku

### ISSUE THREAD

**Issue by sraveh** [flovilmart/parse-image#3]
Hi,

I tried deploying my app to heroku, the parse-image module failed in deployment.

Here is the error:

It looks like the parse-image module is not compatible with Heroku. It tries to use homebrew or sudo to install gm or imagemagick:

remote:        > parse-image@0.0.18 preinstall /tmp/build_9ed95ed63f69c34fc0fa215168b807c2/node_modules/.staging/parse-image-5c1fcece21cc52b861c781521b1fc6aa
remote:        > ./install.sh
remote:
remote:        Cannot install using brew or sudo apt-get
remote:        Please install manually

This appears to be a bug in parse-image's detection, since imagemagick is built into the Heroku stack and doesn't need to be installed:

$ heroku run convert --version
Running convert --version on shrouded-oasis-52482... up, run.8515
Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

Thanks,
Simon

**Comment by flovilmart** [comment]
Hi Simon, the module doesn't fail installing IMHO, but just skips the pre-install. There is a check to make sure that both convert AND gm are installed and available. It seems that gm is not installed.

However, there is a build pack for Graphics Magick, https://github.com/mcollina/heroku-buildpack-graphicsmagick

Can you try that?

**Comment by sraveh** [comment]
@flovilmart 

Thanks for the help, yes, installing the build pack solve the issue. 

Thanks,
Simon

**Comment by flovilmart** [comment]
Could you provide instructions for heroic and put it in the readme?
