### ISSUE TITLE
Image.data() used to return a Promise

### ISSUE THREAD

**Issue by gfpacheco** [flovilmart/parse-image#9]
Now it return the data directly.

The change is probably good, but it breaks 100% compatibility with old cloud code.

In my case I changed `image.data().then(function(data){...});` with `var data = image.data();`

**Comment by 5amfung** [comment]
@flovilmart When you get a chance, please merge #10 ?

**Comment by flovilmart** [comment]
Why this change? This will also break with all people using it now.

**Comment by gfpacheco** [comment]
As I said the old Parse Image module works that way, returning a promise instead of the data itself.

And the change won't break if you use it in the middle of a promise chain:

```
...
}).then(function(image) {
    return image.data();
}).then(function(data) {
...
```

But the way it is now I can't do

```
...
}).then(function(image) {
    return image.data().then(function(data) {
...
```
